/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editadordecodigo.ui;

import editadordecodigo.archivos.Archivo;
import editadordecodigo.archivos.ManejadorDeArchivos;
import editadordecodigo.compilador.Compilador;
import editadordecodigo.lenguaje.ControlLenguajes;
import editadordecodigo.lenguaje.Lenguaje;
import editadordecodigo.lenguaje.ManejadorEntrada;
import editadordecodigo.ui.backend.Manuales;
import editadordecodigo.ui.backend.NumeroLinea;
import editadordecodigo.ui.backend.TextoDeAcciones;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JMenuItem;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

/**
 *
 * @author sergio
 */
public class Principal extends javax.swing.JFrame {
    
    private NumeroLinea nl;
    private ControlLenguajes cl;
    private ManejadorDeArchivos mda;
    private Compilador compi;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        cl = new ControlLenguajes();
        cl.cargarPrueba();
        mda = new ManejadorDeArchivos();
        ManejadorEntrada me = new ManejadorEntrada();
        agregarLenguajes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtErrores = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtOutput = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        lblSeleccionado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuLenguajes = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuTabla = new javax.swing.JMenuItem();
        menuPila = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editador De Codigo");
        setBackground(new java.awt.Color(0, 0, 51));

        tabs.setForeground(new java.awt.Color(0, 0, 102));
        tabs.setOpaque(true);
        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        txtErrores.setBackground(new java.awt.Color(0, 0, 0));
        txtErrores.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtErrores);

        jTabbedPane1.addTab("Errores", jScrollPane1);

        txtOutput.setBackground(new java.awt.Color(0, 0, 0));
        txtOutput.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(txtOutput);

        jTabbedPane1.addTab("Output", jScrollPane2);

        jLabel1.setText("Lenguaje:");

        lblSeleccionado.setText("----");

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Nuevo");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Abrir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("Guardar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setText("Guardar Como");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Salir");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        MenuLenguajes.setText("Lenguajes");
        jMenuBar1.add(MenuLenguajes);

        jMenu3.setText("Ejecutar");

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setText("Compilar");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setText("Cargar Lenguaje");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Borrar Lenguaje");
        jMenu3.add(jMenuItem8);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Ver");

        menuTabla.setText("Tabla LARL");
        menuTabla.setEnabled(false);
        menuTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTablaActionPerformed(evt);
            }
        });
        jMenu4.add(menuTabla);

        menuPila.setText("Pila");
        menuPila.setEnabled(false);
        menuPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPilaActionPerformed(evt);
            }
        });
        jMenu4.add(menuPila);

        jMenuBar1.add(jMenu4);

        jMenu2.setText("Ayuda");

        jMenuItem9.setText("Manual De Usuario");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Manual Tecnico");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem10);

        jMenuItem11.setText("Instalacion y Desinstalacion");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblSeleccionado, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblSeleccionado))
                .addGap(10, 10, 10)
                .addComponent(tabs, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));

    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        EleccionDeLenguaje el = new EleccionDeLenguaje(this, true, cl.getLenguajes());
        el.setVisible(true);
        if (el.getLenguajeElejido() != null) {
            IngresoDeNombre idn = new IngresoDeNombre(this, rootPaneCheckingEnabled, el.getLenguajeElejido());
            idn.setVisible(true);
            if (idn.getArchivo() != null) {
                agregarArchivo(idn.getArchivo());
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        ManejadorEntrada me = new ManejadorEntrada();
        me.cargarLenguaje(this);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setDialogTitle("Seleccione El Archivo que desee abrir");

        jfc.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jfc.showOpenDialog(this);
        File file = jfc.getSelectedFile();
        if (file != null) {
            mda.abrirArchivo(file, cl.getLenguajes(), this);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
        lblSeleccionado.setText(mda.getArchivos().get(tabs.getSelectedIndex()).getLenguaje().getNombre());
    }//GEN-LAST:event_tabsStateChanged

    private void menuTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTablaActionPerformed
        TablaLALR tabla = new TablaLALR(mda.getArchivos().get(tabs.getSelectedIndex()).getLenguaje());
        tabla.setVisible(true);
    }//GEN-LAST:event_menuTablaActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        Archivo archivoACompilar = mda.getArchivos().get(tabs.getSelectedIndex());
        compi = new Compilador(archivoACompilar.getLenguaje(), archivoACompilar.getText(), this);
        compi.compilar();
        menuPila.setEnabled(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void menuPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPilaActionPerformed
        if (compi != null) {
            Pila pila = new Pila(compi.obtenerPila());
            pila.setVisible(true);
            agregarLenguajes();
        }
    }//GEN-LAST:event_menuPilaActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        Manuales manualUsuario= new Manuales();
        manualUsuario.abrirManualDeUsuario();
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        Manuales manualTecnico= new Manuales();
        manualTecnico.abrirManualDeTecnico();
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        Manuales manualInstalacion= new Manuales();
        manualInstalacion.abrirManualDeInstalacion();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        mda.guardarArchivo(tabs.getSelectedIndex(),this);
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        mda.guardarArchivoComo(tabs.getSelectedIndex(),this);
    }//GEN-LAST:event_jMenuItem4ActionPerformed
    private void agregarLenguajes() {
        for (int i = 0; i < cl.getLenguajes().size(); i++) {
            javax.swing.JMenuItem menuNuevo = new JMenuItem();
            final Lenguaje len= cl.getLenguajes().get(i);
            
            menuNuevo.setText(cl.getLenguajes().get(i).getNombre());
            menuNuevo.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    abrirInfoLenguaje(evt,len);
                }
            });
            MenuLenguajes.add(menuNuevo);
        }
    }
    
    private void abrirInfoLenguaje(java.awt.event.ActionEvent evt, Lenguaje lenguaje) {        
        InfoLenguaje infoLenguaje = new InfoLenguaje(lenguaje);
        infoLenguaje.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    private void contarLineas(JScrollPane jsp, JTextPane txtPrin) {
        nl = new NumeroLinea(txtPrin);
        jsp.setRowHeaderView(nl);
        
    }
    
    public void escribirEnErrores(String text) {
        TextoDeAcciones.appendToPane(txtErrores, text, Color.red, false);
    }
    
    public  void agregarArchivo(Archivo archivo) {
        mda.addArchivo(archivo);
        JScrollPane jsp = new JScrollPane();
        jsp.setViewportView(archivo);
        jsp.setVisible(true);
        tabs.add(archivo.getNombre() + archivo.getLenguaje().getExtension(), jsp);
        contarLineas(jsp, archivo);
        tabs.setSelectedIndex(tabs.getTabCount() - 1);
        if (!menuTabla.isEnabled()) {
            menuTabla.setEnabled(true);
        }
    }
    
    public JTextPane getjTxtErrores() {
        return txtErrores;
    }
    
    public ControlLenguajes getControlLenguajes() {
        return cl;
    }
    
    public JTextPane getTxtOutput() {
        return txtOutput;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuLenguajes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblSeleccionado;
    private javax.swing.JMenuItem menuPila;
    private javax.swing.JMenuItem menuTabla;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTextPane txtErrores;
    private javax.swing.JTextPane txtOutput;
    // End of variables declaration//GEN-END:variables
}
