
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Aug 18 22:32:40 CST 2020
//----------------------------------------------------

package editadordecodigo.cup;

/** CUP generated class containing symbol constants. */
public class SimbolosLenguaje {
  /* terminals */
  public static final int puntoYComa = 8;
  public static final int Entero = 33;
  public static final int suma = 11;
  public static final int ampersand = 24;
  public static final int Id = 32;
  public static final int qMark = 10;
  public static final int dosPuntos = 28;
  public static final int corcheteC = 22;
  public static final int lanzamiento = 5;
  public static final int corcheteA = 21;
  public static final int coma = 25;
  public static final int igual = 23;
  public static final int Codigo = 38;
  public static final int NumeroVersion = 34;
  public static final int extension = 6;
  public static final int sTerminal = 26;
  public static final int Cadena = 35;
  public static final int EOF = 0;
  public static final int comillas = 18;
  public static final int nombre = 2;
  public static final int error = 1;
  public static final int op = 12;
  public static final int Anything = 36;
  public static final int autor = 4;
  public static final int blanco = 17;
  public static final int letras = 14;
  public static final int numeros = 13;
  public static final int llaveC = 30;
  public static final int llaveA = 29;
  public static final int saltoDeLinea = 15;
  public static final int Extension = 31;
  public static final int parentesisC = 20;
  public static final int separador = 7;
  public static final int parentesisA = 19;
  public static final int asterisco = 9;
  public static final int tab = 16;
  public static final int Fuente = 37;
  public static final int version = 3;
  public static final int no = 27;
}

